config/routes.rb
Rails.application.routes.draw do
  get 'idcodes/new'

  get 'idcodes/create'

  get 'idcodes/update'

  get 'idcodes/edit'

  get 'idcodes/destroy'

  get 'idcodes/index'

  get 'idcodes/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'items/create'

  get 'items/update'

  get 'items/edit'

  get 'items/destroy'

  get 'items/index'

  get 'items/show'

  get 'items/new'

  get 'about/index'

  get 'about' => 'about#index'

  root 'items#index'

  

  resources :items
  resources :idcodes
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items

	validates :name, presence: true,
	length: {minimum 2}
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :category
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = "About Us";
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add New Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save

    redirect_to categories_path
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
def category_params
   params.require(:category).permit(:name)
end
end

app/controllers/idcodes_controller.rb
class IdcodesController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @page_title = 'Add New Item'
    @item = Item.new
    @category = Category.new
  end

  def create
    @item = Category.new(item_params)
    @item.save

    redirect_to items_path
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
  def item_params
   params.require(:item).permit(:name, :category_id, :price, :buy)
end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/idcodes_helper.rb
module IdcodesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>
We are a company that specializes on electrical equipment.
Not just common tools, but also DYI kits and much more. If there is something you would like to see here, we will be glad to hear from you!</p>

<div class="well"> 
	<ul>
	<h3>Contact Details:</h3>
	<li> Elektro Store </li>
	<li> Heiligenstadter Strasse 144/* </li>
	<li> Austria, Wien, 1190 </li>
	<li> Call: +436606339026 </li>
	<li> Email: support@elektro.com </li>
</ul>
</div>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h2>Add New Category</h2>



<%= form_for @category do |f| %>

<div class="form-group">
	<%= f.label :name %><br />
	<%= f.text_field :name, class:'form-control' %><br />
</div>

<%= f.submit "Submit", class:'btn btn-primary' %>
<%link_to "Cancel", categories_path, class:'btn btn-default' %>

<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/idcodes/create.html.erb
<h1>Idcodes#create</h1>
<p>Find me in app/views/idcodes/create.html.erb</p>

app/views/idcodes/destroy.html.erb
<h1>Idcodes#destroy</h1>
<p>Find me in app/views/idcodes/destroy.html.erb</p>

app/views/idcodes/edit.html.erb
<h1>Idcodes#edit</h1>
<p>Find me in app/views/idcodes/edit.html.erb</p>

app/views/idcodes/index.html.erb
<h1>Idcodes#index</h1>
<p>Find me in app/views/idcodes/index.html.erb</p>

app/views/idcodes/new.html.erb
<h2> Add New ID Code </h2>

app/views/idcodes/show.html.erb
<h1>Idcodes#show</h1>
<p>Find me in app/views/idcodes/show.html.erb</p>

app/views/idcodes/update.html.erb
<h1>Idcodes#update</h1>
<p>Find me in app/views/idcodes/update.html.erb</p>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<div id="items-index">
	<div class="row">
		<div class="col-md-3 col-sm-3">
			
		<h3>USB Cable</h3>
		<%= image_tag('covers/2.jpg') %>
		<%= link_to 'Read More', item_path(1), class:'btn btn-primary' %>
		</div>

		<div class="col-md-3 col-sm-3">
			<h3>Micro Board</h3>
		<%= image_tag('covers/1.jpg') %>
		<%= link_to 'Read More', item_path(1), class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>Vintage Synthesizer</h3>
		<%= image_tag('covers/8.jpg') %>
		<%= link_to 'Read More', item_path(1), class:'btn btn-primary' %>
		</div>
	</div>
	</div>

	<div id="items-index">
	<div class="row">
<div class="col-md-3 col-sm-3">
	<h3>USB Stick</h3>
		<%= image_tag('covers/7.jpg') %>
		<%= link_to 'Read More', item_path(1), class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>Iphone Cable</h3>
		<%= image_tag('covers/5.jpg') %>
		<%= link_to 'Read More', item_path(1), class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
		</div>
	</div>
</div>

app/views/items/new.html.erb
<h2> Add New Item </h2>

<%= form_for @item do |f| %>

<div class="form-group">
	<%= f.label :name %><br />
	<%= f.text_field :name, class:'form-control' %><br />
</div>

<div class="form-group">
	<%= f.label :category %><br />
	<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br />
</div>


<div class="form-group">
	<%= f.label :price %><br />
	<%= f.text_field :price, class:'form-control' %><br />
</div>

<div class="form-group">
	<%= f.label :buy %><br />
	<%= f.text_field :buy, class:'form-control' %><br />
</div>



<%= f.submit "Submit", class:'btn btn-primary' %>
<%link_to "Cancel", items_path, class:'btn btn-default' %>


<% end %>

app/views/items/show.html.erb
<div id="items-show">
	<h2>USB Cable</h2>
	<div class="items-show-left">
		<%= image_tag('covers/2.jpg') %>
	</div>
	<div class="items-show-right">
		<h3> Item Info:</h3>
		<ul>
			<li><strong>Category:</strong>USB Cable</li>
			<li><strong>ID Code:</strong>23834</li>
			<li><strong>Material:</strong>Standard</li>
			<li><strong>Color:</strong>Black</li>
			<li><strong>Length:</strong>1M</li>
</ul>
	<%=link_to "Buy for $3", 'http://www.ebay.com', class:'btn btn-success', target:'_blank' %>
</div>
<div class= "clearfix"></div>
<h3> Info: </h3>
<p> Compatible with your devices: camera, phone .. </p>
</div>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title ? @page_title : 'Welcome!' %> | Elektro Store </title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<% params[:controller] == 'Home' ? 'active' : '' %>"><%= link_to 'Home', root_path%></li>
            <li class="<% params[:controller] == 'About' ? 'active' : '' %>"><%= link_to 'About', about_path%></li>
        </ul>
         <ul class="nav navbar-nav navbar-right">

            <li class="dropdown">
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Add New<span class="caret"></span></a>
            	<ul class="dropdown-menu" role="menu">
            		<li><%= link_to "Item", new_item_path %></li>
            		<li><%= link_to "Category", new_category_path %></li>
            		<li><%= link_to "ID", new_idcode_path %></li>
          </ul>
      </li>
  </ul>
        </div><!--/.nav-collapse -->
      
    </div>
</div>


  <header>
  	<div class="container">
  		<h1>Elektro Store <small><%= @page_title ? @page_title : 'Welcome!' %></small></h1>
  	</div>
  </header>

  <section>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<%= yield  %>
			</div>
			<div id="wrapper">
				<div id="sidebar-wrapper">
					
						<li class="sidebar-brand">
				<%= render 'partials/sidebar' %>
			</li>
		
	</div>
	<div id="page-content-wrapper">
		<div class="page-content">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						
					</div></div></div></div></div></div>

<footer>

	<div class="container">
		<p> Copyright &copy; Elektro INC. 2017, All Rights Reserved</p>
				</div>
			</footer>
			</div>
			
		</div>
	</div>
</section>


<script src="elektro/app/assets/javascripts/bootstrap.min.js"></script>
    <script>
    $(document).ready(function) () {
		$('.dropdown-toggle').dropdown();
    });
</script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.c">




  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'items' && params[:action] == 'index' || params[:action] == 'show' %>
<div class="list-group">
	<a href="" class="list-group-item">USB Cable</a>
	<a href="" class="list-group-item">Synth</a>
	<a href="" class="list-group-item">Board</a>
	<a href="" class="list-group-item">Iphone Cable</a>
</div>

<% end %>